modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Rearth/Drone_Buddies/issues"
license = "CC-BY-4.0"

[[mods]]
modId = "drones"
version = "${version}"
displayName = "Modular Drones"
authors = "Me! - rearth"
description = '''
Small mod that allows the player to build modular drones.
'''
logoFile = "assets/drones/icon.png"

[[dependencies.drones]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drones]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drones]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "drones.mixins.json"
